targets:
  $default:
    builders:
      l10n_mapper_generator:l10n_mapper_builder:
        enabled: true  # enables or disables the builder
        options:
          l10n: true # optional default - true
          locale: true # optional default - true
          parseL10n: true # optional default - true
          message: "Translation key not found!" # optional default - null

